   SUBROUTINE READLA(STARTFILE,NUDSR,TIMER,X)
C
C----------------------------------------------------------------
C
      IMPLICIT REAL*8(A-H,O-Z)
      CHARACTER*1 CF,CFS
      CHARACTER*2 CRR
      CHARACTER*40 STARTFILE
      PARAMETER (NM=5500)
      PARAMETER (NMT=50)
C
      DIMENSION X(*)
C
      COMMON/LOG/LCALC,LWRITE,L3,LVAR,LDY,LT,L7,L8,L9,L10
      COMMON/PARI/RA,TA,PR,PM,ETA,C,OM,FTW,FTG,MF
      COMMON/NPARI/M0,NTV,NTH,LTV,LTH,KTV,KTH,LEV,LRB,LD
ccc   COMMON/NUM/RELE,EPS,ALPH,NITMAX,NJA
      COMMON/NUM/RELE,EPS,ALPH,STOER,NITMAX,NJA
      COMMON/DIM/NDV,NDW,NDT,NDH,NDG,ND
      COMMON/DIMS/NDVS,NDWS,NDTS,NDHS,NDGS,NDS
      COMMON/QNU/NMC,L(NM),M(NM),N(NM),K(NM),CF(NM),CRR(NM)
      COMMON/QNUS/NMSC,LS(NM),MS(NM),NS(NM),CFS(NM)
ccc   COMMON/READD/NKZR
      COMMON/QNUVI/NUC,NUOM
      COMMON/TINT/DT,TIME0,NST,NTW,NDTW,NDTPW,NKWT,IKWT(NMT)
C
      IF( NM.NE.NMC ) THEN
         WRITE(*,*) 'WRONG DIMENSION NM IN READP.'
         STOP
      ENDIF
C
C-- IF LRT.EQ.0 WE ARE LOOKING FOR THE RIGHT NUMBER OF DATASET NUDSR,
C-- IF LRT.EQ.1 WE ARE LOOKING FOR THE RIGHT TIME.
C
      OPEN(12,FILE=STARTFILE,STATUS='old')
C              
C-- COUNTER AND LOGICALS SET TO ZERO:
      NKZR=0
C
C-- LST IS FORMAT PARAMETER ( L=1 FOR HIRSCHING FORMAT ) ,
C   LCALCI TELLS HOW THE INPUTFILE HAS BEEN CALCULATED:
      READ(12,*) LST,LCALC
C
C-- FUER LCALC.EQ.5 ODER LCALC.EQ.6 LIEGT ZEITINTEGRATION VOR ,
C   D.H. VERSCHIEDENEN ZEITEN MUESSEN IM INPUTFILE DURCH
C   READLA GESUCHT WERDEN. (LT=1), LTR=1 ZEIGT AN , DASS
C   ZEITINTEGRATION VORLIEGT UND DIE ZEIT GELESEN WERDEN MUSS:
      IF( LCALC.EQ.5 .OR. LCALC.EQ.6 ) THEN
         LT=1
         LTR=1
      ELSE
         LT=0
         LTR=0
      ENDIF
C
C-- READH READS THE HEADER OF THE INPUTFILE AND DETERMINS WETHER
C   THE DATASET (NUDS,TIME) IS THE RIGHT ONE (LDR=1):
      CALL READH(12,LTR,NUDSR,TIMER,NUDS,TIME,LDR)
C
C
C-- LOOKING FOR THE RIGHT DATASET:
      DO 1000 I=1,1000
C
C----- READD READS FULL SET OF COEFFITIENTS:
         CALL READD(12,LDR,ND,X,CF,CRR,L,M,N,K,
     &                      EVPM,EVPF,EVTM,DNU,EVTF,EMPM,EMPF,EMTM,EMTF)
C
         IF( LDR.EQ.1 ) GOTO 1200
C
C---- READP READS THE DATASETNUMBER, TIME IF GIVEN (LT=1) AND 
C     NEW PARAMETERS FOR LT.NE.1 , LDR IS DETERMINED:
c --------- redit
c         CALL READP(12,LST,LTR,NUDSR,TIMER,NUDS,TIME,LDR,LEND)
c         IF( LEND.EQ.1 ) GOTO 1100
C
1000  CONTINUE
1100  CONTINUE
c      WRITE(*,'('' SORRY, SET '',I4,D14.4,'' NOT FOUND'')') NUDSR,TIMER
c      STOP
1200  CONTINUE

      if(ND.GT.NM) then
        write(*,*) 'To small dimension NM in READLA'
        stop
      endif
      TA=TA**2
C
      LSX=1
      CALL SORTK(ND,LSX,X,CF,CRR,L,M,N,K,NUC,NUOM)
      CALL RDIM(ND,CF,CRR,L,M,N,K,CFS,LS,MS,NS,
     &                  NDV,NDW,NDT,NDH,NDG,NDVS,NDWS,NDTS,NDHS,NDGS,NDS)
C
      CLOSE(12)
C
      RETURN
      END
C
C-------------------------------------------------------------------------
C-- END OF SUBROUTINE READLA
C-------------------------------------------------------------------------
! vim: tabstop=3:softtabstop=3:shiftwidth=3:expandtab
