   !----------------------------------------------------------------
   SUBROUTINE READLA(STARTFILE,NUDSR,TIMER,X)
      IMPLICIT REAL*8(A-H,O-Z)
      CHARACTER*1 CF,CFS
      CHARACTER*2 CRR
      CHARACTER*40 STARTFILE
      double precision, intent(in):: x(:)

      COMMON/LOG/LCALC,LWRITE,L3,LVAR,LDY,LT,L7,L8,L9,L10
      COMMON/PARI/RA,TA,PR,PM,ETA,C,OM,FTW,FTG,MF
      COMMON/NPARI/M0,NTV,NTH,LTV,LTH,KTV,KTH,LEV,LRB,LD
      COMMON/NUM/RELE,EPS,ALPH,STOER,NITMAX,NJA
      COMMON/DIM/NDV,NDW,NDT,NDH,NDG,ND
      COMMON/DIMS/NDVS,NDWS,NDTS,NDHS,NDGS,NDS
      COMMON/QNU/NMC,L(NM),M(NM),N(NM),K(NM),CF(NM),CRR(NM)
      COMMON/QNUS/NMSC,LS(NM),MS(NM),NS(NM),CFS(NM)
      COMMON/QNUVI/NUC,NUOM
      COMMON/TINT/DT,TIME0,NST,NTW,NDTW,NDTPW,NKWT,IKWT(NMT)

      IF( NM.NE.NMC ) THEN
         WRITE(*,*) 'WRONG DIMENSION NM IN READP.'
         STOP
      ENDIF

      !-- IF LRT.EQ.0 WE ARE LOOKING FOR THE RIGHT NUMBER OF DATASET NUDSR,
      !-- IF LRT.EQ.1 WE ARE LOOKING FOR THE RIGHT TIME.
      OPEN(12,FILE=STARTFILE,STATUS='old')

      !-- COUNTER AND LOGICALS SET TO ZERO:
      NKZR=0

      !-- LST IS FORMAT PARAMETER ( L=1 FOR HIRSCHING FORMAT ) ,
      !   LCALCI TELLS HOW THE INPUTFILE HAS BEEN CALCULATED:
      READ(12,*) LST,LCALC

      !-- FUER LCALC.EQ.5 ODER LCALC.EQ.6 LIEGT ZEITINTEGRATION VOR ,
      !   D.H. VERSCHIEDENEN ZEITEN MUESSEN IM INPUTFILE DURCH
      !   READLA GESUCHT WERDEN. (LT=1), LTR=1 ZEIGT AN , DASS
      !   ZEITINTEGRATION VORLIEGT UND DIE ZEIT GELESEN WERDEN MUSS:
      IF( LCALC.EQ.5 .OR. LCALC.EQ.6 ) THEN
         LT=1
         LTR=1
      ELSE
         LT=0
         LTR=0
      ENDIF

      !-- READH READS THE HEADER OF THE INPUTFILE AND DETERMINS WETHER
      !   THE DATASET (dataSetNumber,TIME) IS THE RIGHT ONE (LDR=1):
      CALL READH(12,LTR,NUDSR,TIMER,dataSetNumber,TIME,LDR)

      !-- LOOKING FOR THE RIGHT DATASET:
      DO I=1,1000
         !----- READD READS FULL SET OF COEFFITIENTS:
         CALL READD(12,LDR,ND,X,CF,CRR,L,M,N,K, EVPM,EVPF,EVTM,DNU,EVTF,EMPM,EMPF,EMTM,EMTF)
         IF( LDR.EQ.1 ) exit
      enddo

      if(ND.GT.NM) then
        write(*,*) 'To small dimension NM in READLA'
        stop
      endif
      TA=TA**2

      LSX=1
      CALL SORTK(ND,LSX,X,CF,CRR,L,M,N,K,NUC,NUOM)
      CALL RDIM(ND,CF,CRR,L,M,N,K,CFS,LS,MS,NS, &
                       NDV,NDW,NDT,NDH,NDG,NDVS,NDWS,NDTS,NDHS,NDGS,NDS)
      CLOSE(12)
   END SUBROUTINE READLA
! vim: tabstop=3:softtabstop=3:shiftwidth=3:expandtab
